dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: go

go:
    - 1.7

gobuild_args: -v -tags "mysql"

services:
    - mysql

before_script:
    - mysql -u root -e 'create database manage;'
    - mysql -u root manage < $HOME/gopath/src/github.com/MikeK123/dingo/test/database.sql
