dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: go

go:
    - 1.6

before_install:
    - mkdir $HOME/gopath/src/github.com/maxzerbini/prjtest

services:
    - mysql

before_script:
    - mysql -u root -e 'create database customers;'
    - mysql -u root customers < $HOME/gopath/src/github.com/maxzerbini/dingo/test/database.sql
