language: go

go:
    - 1.6
    - tip

services:
    - mysql

before_script:
    - mysql -e 'create database customers;'
    - mysql customers < $HOME/gopath/src/github.com/maxzerbini/dingo/test/database.sql
